// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProyectoFinalP1.Models;

#nullable disable

namespace ProyectoFinalP1.Migrations
{
    [DbContext(typeof(FinalContext))]
    partial class FinalContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.4");

            modelBuilder.Entity("ProyectoFinalP1.Models.Cliente", b =>
                {
                    b.Property<int>("IdCliente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("Id_cliente");

                    b.Property<string>("Apellido")
                        .HasColumnType("text");

                    b.Property<string>("Cedula")
                        .HasColumnType("text");

                    b.Property<string>("Correo")
                        .HasColumnType("text");

                    b.Property<string>("Edad")
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .HasColumnType("text");

                    b.Property<string>("Telefono")
                        .HasColumnType("text");

                    b.HasKey("IdCliente")
                        .HasName("PK__Clientes__FCE03992BA80119C");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("ProyectoFinalP1.Models.Producto", b =>
                {
                    b.Property<int>("IdProductos")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("Id_productos");

                    b.Property<string>("Categoria")
                        .HasColumnType("text");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .HasColumnType("text");

                    b.Property<string>("Precio")
                        .HasColumnType("text");

                    b.Property<string>("Stock")
                        .HasColumnType("text")
                        .HasColumnName("# Stock");

                    b.HasKey("IdProductos")
                        .HasName("PK__Producto__2CB55F329A3EA5AE");

                    b.ToTable("Productos");
                });

            modelBuilder.Entity("ProyectoFinalP1.Models.Sucursale", b =>
                {
                    b.Property<int>("IdSucursal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("Id_sucursal");

                    b.Property<string>("Direccion")
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .HasColumnType("text");

                    b.Property<string>("Telefono")
                        .HasColumnType("text");

                    b.HasKey("IdSucursal")
                        .HasName("PK__Sucursal__A71B7D48592E80B9");

                    b.ToTable("Sucursales");
                });

            modelBuilder.Entity("ProyectoFinalP1.Models.Vendedore", b =>
                {
                    b.Property<int>("IdVendedor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("Id_vendedor");

                    b.Property<string>("Apellido")
                        .HasColumnType("text");

                    b.Property<string>("Cedula")
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .HasColumnType("text");

                    b.Property<string>("Salario")
                        .HasColumnType("text");

                    b.Property<string>("Telefono")
                        .HasColumnType("text");

                    b.HasKey("IdVendedor")
                        .HasName("PK__Vendedor__5257D23D5C09A12F");

                    b.ToTable("Vendedores");
                });
#pragma warning restore 612, 618
        }
    }
}
